version: '2.2'
services:
  # Spezifikation des Kalender MS
  dvp:
    build: .
    depends_on:
    - dvp_db
    ports:
    - "8020"
    networks:
    - dvp_ms_db
    - fae-message-broker_backend
  # Spezifikation der Datenbank
  dvp_db:
    image: postgres:10.1 # Basis Image
    volumes:
    - dvp_db:/var/lib/postgresql/data # Volume um Daten persistent zu speichern. Alle Daten aus dem Pfad (rechts) werden in das Volume abgelegt.
    environment: # Konfiguration über env-Variablen
    - POSTGRES_PASSWORD=_dvpService_2018
    - POSTGRES_USER=dvpService
    - POSTGRES_DB=dvpService
    - PGDATA=/var/lib/postgresql/data/pgdata
    - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    restart: always # Bei einem Absturz soll die DB immer neu starten.
    networks: # Netzwerk für die DB und dem Microservice
    - dvp_ms_db
volumes: # Allgemeine Volumes für das Projekt
  dvp_db: {}
networks:
  dvp_ms_db:
    driver: bridge
  fae-message-broker_backend:
    external: true